name: branch-1 workflow

on:
  push:
    branches:
      - backup-1  # modify

jobs:
  backup:
    name: Backup to Codecommit 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials for CodeCommit access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::278445542791:role/testing-purpose # Codecommit
          role-session-name: GithubActiontrigger
          aws-region: ap-south-1  # modify

      - name: Install git-remote-codecommit (utility)
        run: pip install git-remote-codecommit
      - name: adding mirror remote
        run: git remote add mirror codecommit::ap-south-1://mig-backup # add codecommit https(grc) url
      - name: Pushing to codecommit
        run: git push --force --prune mirror backup-1  # provide the branch name

  build:
    name: Build Docker Image and Push to ECR & Snyk scan
    runs-on: ubuntu-latest 
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials for ECR access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::278445542791:role/testing-purpose # Codecommit
          role-session-name: GithubActiontrigger
          aws-region: ap-south-1  # modify

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Images
        run: docker build -t github-repo .
  
      - name: Push Docker Image to ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: github-repo   #modify
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag github-repo $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


        # - name: Run Snyk to check Docker image for vulnerabilities
        #   continue-on-error: true
        #   uses: snyk/actions/docker@master
        #   env:
        #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        #   with:
        #     image: 306727587552..dkr.ecr.us-east-1.amazonaws.com/github-repo:${{ github.sha }}
        #     args: --file=Dockerfile
