name: pipeline

on:
  push:
    branches:
      - backup

jobs:
  snyc:
    name: Backup to Codecommit & Push to ECR and Snyk scan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure AWS credentials for CodeCommit access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # aws codecommit access
          role-session-name: GithubActiontrigger
          aws-region: us-east-1

      - name: Build Docker Images and Push to Codecommit
        run: | 
          docker build --build-arg AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
          --build-arg AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
          --build-arg AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN \
          -t github-repo .

      - name: Configure AWS credentials for ECR
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  # provide role access id for ecr access
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker Image to ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ci-pipe-repo-backup
          IMAGE_TAG: ${{ github.sha }}
        run: |  
          docker tag github-repo $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
