name: workflow

on:
  push:
    branches:
      - '**'  

jobs:
  build:
    name: Build Docker Image and Push to ECR & Snyk scan
    if: github.event.ref == 'refs/heads/main' 
    runs-on: ubuntu-latest 
    permissions:
        id-token: write
        contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials for ECR access
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::278445542791:role/testing-purpose # modify ECR ARN
          role-session-name: GithubActiontrigger
          aws-region: ap-south-1  # modify 

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Images
        run: docker build -t image .
  
      - name: Push Docker Image to ECR
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: github-repo   #modify
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag imagee $REGISTRY/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  snyk_scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Docker image 
      run: docker build -t image-to-test .
    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: image-to-test
        args: --severity-threshold=high

# BACKUP TO ECR step will run whenever there's a commit to the main branch. The SYNK SCAN step will run for all branches & I have removed BACKUP TO CODECOMMIT steps.